import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="page p-6">
      <div className="headertext-white py-4">
        <div className="container mx-auto">
          <p className="title text-2xl font-bold">Privacy Policy for Kalyani Online Matka App</p>
        </div>
      </div>

      <div className="translations-content-container py-8">
        <div className="">
          <div className="tab-content translations-content-item en visible" id="en">
            <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
            <p className="text-gray-700 mb-2">Last updated: January 29, 2025</p>
            <p className="mb-4">This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p className="mb-4">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            
            <h2 className="text-2xl font-bold mt-6 mb-4">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
            <p className="mb-4">The words with capitalized initials have meanings defined under specific conditions. These definitions apply regardless of whether they appear in singular or plural.</p>

            <h3 className="text-xl font-semibold mb-2">Definitions</h3>
            <ul className="list-disc list-inside mb-6">
              <li><strong>Account:</strong> A unique account created for You to access our Service.</li>
              <li><strong>Application:</strong> Kalyani Online Matka App, the software program provided by the Company.</li>
              <li><strong>Company:</strong> Refers to Kalyani Online Matka App.</li>
              <li><strong>Country:</strong> Refers to Rajasthan, India.</li>
              <li><strong>Device:</strong> Any device that can access the Service (e.g., computer, cellphone, tablet).</li>
              <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service:</strong> Refers to the Application.</li>
              <li><strong>Service Provider:</strong> A natural or legal person who processes data on behalf of the Company.</li>
              <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure itself.</li>
            </ul>

            <h2 className="text-2xl font-bold mt-6 mb-4">Collecting and Using Your Personal Data</h2>
            <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
            <h4 className="text-lg font-medium mb-2">Personal Data</h4>
            <p className="mb-4">We may ask You to provide Us with personally identifiable information, including but not limited to:</p>
            <ul className="list-disc list-inside mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>
            
            <h4 className="text-lg font-medium mb-2">Usage Data</h4>
            <p className="mb-4">Usage Data is collected automatically and may include information such as IP address, browser type, and pages visited.</p>
            
            <h3 className="text-xl font-semibold mb-2">Use of Your Personal Data</h3>
            <ul className="list-disc list-inside mb-6">
              <li><strong>To provide and maintain our Service:</strong> Including monitoring usage.</li>
              <li><strong>To manage Your Account:</strong> Enabling access to different functionalities.</li>
              <li><strong>For the performance of a contract:</strong> Managing purchase contracts for products or services.</li>
              <li><strong>To contact You:</strong> Via email, calls, SMS, or push notifications.</li>
              <li><strong>To provide updates and offers:</strong> About products, services, or events.</li>
            </ul>

            <h2 className="text-2xl font-bold mt-6 mb-4">Children's Privacy</h2>
            <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect information from children under 13.</p>

            <h2 className="text-2xl font-bold mt-6 mb-4">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <p className="mb-4">By email: <a href="mailto:hello.kalyanionline12@gmail.com" className="text-blue-600 hover:underline">hello.kalyanionline12@gmail.com</a></p>
          </div>
        </div>
      </div>
      
      <div className="footer py-4">
        <div className="container mx-auto text-center">
          <p>Generated using <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Free Privacy Policy Generator</a></p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
